name: Monthly Reference Update

on: 
  schedule:
   - cron: '0 0 1 * *'

jobs:
  run-scrapper:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install dependencies
          run: pip install -r ./data/publications/requirements.txt
        - name: Run scrapper
          run: python ./data/publications/scrapper.py
